export const RETRY_BACKOFF_MS = [30_000, 60_000, 120_000, 300_000, 600_000];

/**
 * Prisma `@default(now())` is generated by the query engine and can be a few
 * milliseconds ahead of `Date.now()`. Newly queued jobs would otherwise stay
 * QUEUED until the next poll. Retry backoff starts at 30s, so 1s of slack is safe.
 */
export const DUE_CLOCK_SKEW_MS = 1_000;

export function nextRetryAt(retryCount: number, now = Date.now()): Date {
  const delay = RETRY_BACKOFF_MS[Math.min(retryCount - 1, RETRY_BACKOFF_MS.length - 1)] ?? 600_000;
  return new Date(now + delay);
}

export function dueHorizon(now = Date.now()): Date {
  return new Date(now + DUE_CLOCK_SKEW_MS);
}

export function immediateAvailableAt(now = Date.now()): Date {
  return new Date(now - DUE_CLOCK_SKEW_MS);
}
