-- AlterEnum
ALTER TYPE "AppointmentStatus" ADD VALUE 'COMPLETED';

-- AlterEnum
ALTER TYPE "TimelineCode" ADD VALUE 'SLOT_HELD';
ALTER TYPE "TimelineCode" ADD VALUE 'SLOT_EXPIRED';
ALTER TYPE "TimelineCode" ADD VALUE 'APPOINTMENT_CANCELLED';
ALTER TYPE "TimelineCode" ADD VALUE 'APPOINTMENT_RESCHEDULED';
